---
name: "ğŸ§³ Build Main Definition"

on:
  workflow_call:
    inputs:
      repo-token:
        required: true
        type: string
        description: "The GitHub token to use for the run"


jobs:

  call-bot:
    name: "ğŸ¤– BOT's"
    if: ${{ github.event_name == 'issue_comment' }}
    # if: ${{ github.event.issue.pull_request && contains(github.event.comment.html_url, '/pull/')  }}
    uses: ./.github/workflows/terraform-bot.yml
    secrets: inherit

  plan-terraform:
    name: "ğŸ—“ï¸ Refresh Terraform Plan"
    if: ${{ github.event_name == 'pull_request' }} # TODO: Add file for **/*.tf and **/*.tfvars
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    with:
      repo-token: ${{ inputs.repo-token }}
